name: GiftCode
main: cn.innc11.giftcode.GiftCodePlugin
version: "1.3"
author: "innc"
api: ["1.0.0"]
description: gift code plugin
commands:
  code:
    usage: "/code"
    description: "open the panel of GiftCode"